services:
  mc:
    container_name: mirth_$USER
    image: nextgenhealthcare/connect
    volumes:
      - ./data/mirth/appdata:/opt/connect/appdata
      - ./data/mirth/folder:/var/tmp/
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://db:5432/mirthdb
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=mirthdb
      - DATABASE_PASSWORD=mirthdb
      - DATABASE_MAX_RETRY=2
      - DATABASE_RETRY_WAIT=10000
      - KEYSTORE_STOREPASS=docker_storepass
      - KEYSTORE_KEYPASS=docker_keypass
      - VMOPTIONS=-Xmx512m
    ports:
#      - 8080:8080/tcp
      - 8443:8443/tcp
      - 16661:16661/tcp
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1200M

  db:
    container_name: postgres_$USER
    image: postgres
    environment:
      - POSTGRES_USER=mirthdb
      - POSTGRES_PASSWORD=mirthdb
      - POSTGRES_DB=mirthdb
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    #expose:
    #  - 5432
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 300M

